services:
  app:
    build: .
    container_name: be-pos-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - pos-network

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - pos-network

volumes:
  pg-data:

networks:
  pos-network:
